### ISSUE TITLE
clarification on uploading a provider 

### ISSUE THREAD

**Issue by ilyesAj** [TierMobility/boring-registry#101]
1. can we make an upload of a module/provider on a distant registry not local one ? 
2. I see that uploading a provider is not supported yet using CLI , what dev work should be done on that ? is there any blockers ?

**Comment by oliviermichaelis** [comment]
Hi @ilyesAj !

1. I'm not sure what you mean by distant vs local in your question. `boring-registry` does not need to run on the same machine as Terraform. It could for example run in the cloud, while Terraform runs on your local machine for example. Maybe you could restate your question, so that I can answer it better :)
2. You're right, it's currently not possible yet. I think I might give implementing this a shot this evening

**Comment by ilyesAj** [comment]
hi @oliviermichaelis , thanks for your quick response, 
let me explain a bit more the situation :
- we deployed a boring-registry on k8s and we exposed it via an ingress
- my question is whether `./boring-registry upload` can work from my local machine to upload a module to the distant boring-registry. 
I hope it's clear .

**Comment by oliviermichaelis** [comment]
Thanks, it's a lot clearer now.
The `upload` command actually uploads the modules directly to your storage backend (S3, GCS, MinIO). This means that you need to pass valid credentials for the storage backend to the binary when uploading modules.

**Comment by ilyesAj** [comment]
yep thanks, but I think boring-registry should be the only one accessing/managing S3 bucket. So I as a user I just need to authenticate via static token to boring registry and boring registry will make internally the calls to s3 alongside with some checks to avoid conflicts on upload.

**Comment by oliviermichaelis** [comment]
That would definitely be nice! The implementation would probably be more complex, though.
With the current approach, we can leverage the sophisticated identity and access management services from cloud vendors for uploading modules/providers to the object storage with little effort. In contrast to relying on the static token and the boring-registries implementation of authorization.

Right now, the boring-registry can only serve what's already there. When attackers gain access to one of boring-registry's static auth token, they can only use what's already there, and not inject arbitrary modules to escalate privileges or exfiltrate data. I guess that's part of what makes the boring-registry boring :)

**Comment by ilyesAj** [comment]
agree, it's a different approach ;)
