### ISSUE TITLE
[Bug] Modules publishing to Cloud Storage are not appending extension

### ISSUE THREAD

**Issue by tferraro** [TierMobility/boring-registry#133]
Alo!

Each time a module is published to cloud storage, it returns the following error message:
```
storage: object doesn't exist: failed to locate module
```

To reproduce:
- Generate a minimum example of a module. Using a null_resource local-exec "ls" may suffice
- Run `./boring-registry upload <module-name> --storage-gcs-bucket=<bucket name>`

If checked into the bucket, the file is correctly uploaded. However, it is not recognized by `./boring-registry server` command.

### Origin
I've tracked the origin of the issue to this variable:
https://github.com/TierMobility/boring-registry/blob/main/pkg/storage/gcs.go#L31

This variable is used to create the path on the `GetModule` method https://github.com/TierMobility/boring-registry/blob/main/pkg/storage/gcs.go#L34 used by both server command (to identify versions or download) and the upload command, to return the information of the module & identify it's existence.

On the upload section, this works because the extension is hard-coded to the default variables:
https://github.com/TierMobility/boring-registry/blob/main/pkg/storage/gcs.go#L100

### Results
This causes the whole module functionality to directly not work on GS, as the only way for the boring-registry to recognize the zip is to remove the extension (but leaving the dot, due to the string interpolation of an empty variable).
However, this doesn't work properly with Terraform as not having the extension makes the downloading of the module have undefined behavior.

### Proposed Solution
> I'll try to code this solution and generate a PR, but I wanted to ask how willing we are to accept it 😆 

The issue comes from here:
https://github.com/TierMobility/boring-registry/blob/main/cmd/server.go#L203

This method is setting the storage for both server and upload variations; but on Cloud Storage, it forgets to set the following line: https://github.com/TierMobility/boring-registry/blob/main/cmd/server.go#L212. Therefore, leaving it null.

Also, it would be cool to avoid setting the default value in the upload storage method and directly use this configuration, to keep consistency.

Thanks!

**Comment by oliviermichaelis** [comment]
Hi @tferraro ! First of all, thank you for opening a bug report, investigating the problem and also providing your results in such a detailed manner. It made it really easy to follow along :)

I checked your commit (https://github.com/tferraro/boring-registry/commit/dd27453b76fa9eebc1f3c75f607d06c0df8d00d7) which looks reasonable to me. Please open a PR, I'd be happy to review it :)

**Comment by tferraro** [comment]
Hi @oliviermichaelis! Great, I'll create the PR asap 😄

**Comment by tferraro** [comment]
This was rolled out in version 0.11.1 :) I'm closing the issue! 🙂

**Comment by oliviermichaelis** [comment]
Thanks! The release didn't go through though :/ See this run for details: https://github.com/TierMobility/boring-registry/actions/runs/5666717220/job/15354030090

 I'll have a look at it in ~5h

**Comment by oliviermichaelis** [comment]
A [new release](https://github.com/TierMobility/boring-registry/releases) and also a [new helm chart](https://github.com/TierMobility/boring-registry/pkgs/container/charts%2Fboring-registry) are published with version `0.11.2` :)
