### ISSUE TITLE
Official Docker Image

### ISSUE THREAD

**Issue by C0urante** [TierMobility/boring-registry#27]
There are a few Docker images on Docker Hub ([odise/boring-registry](https://hub.docker.com/r/odise/boring-registry), [bdwyertech/boring-registry](https://hub.docker.com/r/bdwyertech/boring-registry)), but neither seems to be an official image.

It'd be nice to have an official image published on Docker Hub to ensure that new tags get created for new releases, and to limit reliance on unofficial forks of the project.

**Comment by C0urante** [comment]
After taking a look at the CI pipeline it appears I spoke too soon, and an image is already being published to ghcr.io/tiermobility/boring-registry for every tag: https://github.com/TierMobility/boring-registry/blob/a7018f03ed95df1bf24206dc5411acd1bd596e16/.github/workflows/container.yml#L25-L28

Whoops! I'll close this and file a small PR to add that info to the README.

**Comment by C0urante** [comment]
https://github.com/TierMobility/boring-registry/pull/29

**Comment by oliviermichaelis** [comment]
Hi @C0urante, first of all thank you for raising the issues you had while interacting with this project, that's much appreciated! :)

Out of curiosity, are you planning to run the project in plain docker or maybe even kubernetes?

**Comment by C0urante** [comment]
Happy to help! Looking like this project is going to save me a lot of time, thanks for open-sourcing it.

I believe the current plan is to run with Kubernetes.

**Comment by oliviermichaelis** [comment]
Cool! @heimweh had started with a helm chart in #20, would you be interested in using it? If so, we might clean that up and get it merged :)

**Comment by C0urante** [comment]
We might eventually need a Helm chart, but at the moment I don't think it's a must-have for us. That said, if I can find time I'd be happy to give it a try and let you know how it goes if you're looking for feedback!
