### ISSUE TITLE
Alternative module archive formats

### ISSUE THREAD

**Issue by C0urante** [TierMobility/boring-registry#28]
Terraform can handle archives in [several different formats](https://www.terraform.io/language/modules/sources#fetching-archives-over-http), including zip, tar.bz2 (tbz2), tar.gz (tgz), and tar.xz (txz). It'd be nice to have support for these different formats in the registry.

This could potentially be done by checking the backing store for which formats are available for a requested module and then automatically serving a download link corresponding to one of those formats, but the implementation complexity would be high and the value would be dubious since it's unclear how many people would have mixed archive formats in the backing store for their registry.

An alternative could be to add a `--storage-module-archive-format` flag that defaults to `tar.gz` (the [current expected format](https://github.com/TierMobility/boring-registry/blob/a7018f03ed95df1bf24206dc5411acd1bd596e16/pkg/module/storage.go#L33)) but can be used to switch over to zip, tbz2, etc.

**Comment by oliviermichaelis** [comment]
I'm not sure if we really want to support dynamic file format detection right now. But adding the `--storage-module-archive-format` flag makes sense in my opinion :)

We should note that the `upload` command creates `tar.gz` archives right now. So as you mentioned, it makes sense to use it as the default in order to be backward compatible

**Comment by oliviermichaelis** [comment]
I merged the PR, thanks for your contribution!

@heimweh and I want to get some more breaking changes in before we cut the `v0.8.0` release. I hope that is okay for you, please let us know if you need a new release more urgently :)

**Comment by C0urante** [comment]
It'd be nice to know what the planned breaking changes are, though. I just shuffled around some S3 artifacts yesterday to conform to the expected provider path structure with 0.7.0 and I'm going to have to redo all of that now that the structure has changed. Anything else like that going to happen?

**Comment by oliviermichaelis** [comment]
That's hard to estimate for obvious reasons, but I hope that we can release `v0.8` in weeks rather than months :)

 I'm curious, can you elaborate a bit on how you upload your modules and what speaks against the CLI upload command?

**Comment by C0urante** [comment]
We upload our modules to S3 using the AWS CLI. The upload CLI here is a little too opinionated to integrate easily (don't want to have to create an HCL file for every time we upload something), and it's a little more heavyweight to have to pull in the CLI as a dependency in our CI/CD pipeline when the AWS CLI is already baked in and can do what we need. We might use it in the future but at least right now it's easier to just stick with the AWS CLI.
