### ISSUE TITLE
Allow cloud objects to be referenced via HTTP protocol

### ISSUE THREAD

**Issue by C0urante** [TierMobility/boring-registry#37]
The Terraform CLI fails to download modules from S3 even if they're publicly-readable if it can't find any AWS credentials. An easy workaround to this is to serve module sources that use the `https://` scheme, which causes the CLI to use HTTP instead of the S3 protocol to download the module. It'd be nice if there were a flag like `--storage-s3-force-http` that could enable that behavior.

I've taken a brief look at the GCS logic and it seems like `https://` URLs are already being served for GCS objects, but if that's not the case, it's probably worth it to add support for this type of behavior to GCS mode as well.

Does this sound reasonable?

**Comment by oliviermichaelis** [comment]
Hi @C0urante :)

> An easy workaround to this is to serve module sources that use the https:// scheme, which causes the CLI to use HTTP instead of the S3 protocol to download the module.

Could you elaborate further, please? I can't follow you here, unfortunately :/


> The Terraform CLI fails to download modules from S3 even if they're publicly-readable if it can't find any AWS credentials

This is true. The problem is that we would have to figure out somehow that no credentials were passed to the client. I guess we could then use `AnonymousCredentials` (https://github.com/aws/aws-sdk-go-v2/blob/main/aws/credentials.go#L61)

**Comment by C0urante** [comment]
> Could you elaborate further, please? I can't follow you here, unfortunately :/

Sure! Right now, if I try to download a Terraform module sourced from a running Boring Registry instance with `terraform init`, the download will fail if I don't have any AWS credentials on my machine, even if the object in S3 is readable for everyone. However, if Boring Registry adds a prefix of `https://` to the download URL that it gives to the Terraform CLI, then the CLI doesn't look for S3 credentials, and instead just downloads the module by sending a plain GET request to the URL.

This obviously isn't perfect for every situation since a lot of the time, you want the Terraform CLI to use your AWS credentials to access S3 objects. But allowing this behavior to be enabled via a command line flag would be nice for the cases where the artifacts in S3 are publicly available and not all expected Terraform CLI users will have AWS credentials in their environment.

For a concrete example, find an S3 object that's publicly readable and then try to run `terraform init` with this Terraform file on a machine with no AWS credentials:
```
module "example" {
    source = "<bucket>.s3-<region>.amazonaws.com/<key>"
}
```

It should fail. However, if you change the file to this:
```
module "example" {
    source = "https://<bucket>.s3-<region>.amazonaws.com/<key>
}
```
It should succeed.

**Comment by oliviermichaelis** [comment]
Thanks, I got you now :)

Coincidentally I just posted #38 which adds presigned URLs to the S3 storage backend. I think that should allow the clients to download the module in that case.
I haven't tested it yet, though.

**Comment by C0urante** [comment]
@oliviermichaelis I haven't had time to test either but I agree that presigned URLs should address this use case as they are prefixed with a protocol, which should force Terraform to access them like regular URLs and not inject AWS credentials. I'll close this for now but report back if this isn't the case for some reason.

As an aside, presigned URLs are a much more elegant solution to this issue than the hack I proposed. Nice! 🎉
