### ISSUE TITLE
How does authorization with S3 work?

### ISSUE THREAD

**Issue by sanderginn** [TierMobility/boring-registry#5]
Hi guys,

I feel like I'm looking over something obvious here, but I don't understand how access to the S3 bucket is authorized?
I have never worked with AWS products, so perhaps I'm lacking knowledge in that area. FYI, I'm working on a PR that allows a different S3 endpoint to be used; I'd like to try boring registry with a MinIO backend.

**Comment by heimweh** [comment]
Hey @sanderginn, really sorry for the delay here :pray:

Access to the s3 bucket must happen outside of the boring-registry. 
Will make sure to update the README and add some IAM example policy with the actions that boring-registry expects.
I've never tested the boring-registry against MinIO actually, if you get it to work please let us know 🙂

**Comment by sanderginn** [comment]
No worries. In the end our use case for a private registry was not strong enough to warrant the development effort. I've got this project saved for future reference though, I like how you make use of HCL for metadata management. :-)

**Comment by heimweh** [comment]
Closing this for now but feel free to re-open at any time :pray:

**Comment by ptu** [comment]
the aws sdk pulls `AWS_ACCESS_KEY_ID` , `AWS_SECRET_ACCESS_KEY` and `AWS_REGION` from the environment. That how boring registry authenticates against S3 (and now MINIO) #10
