### ISSUE TITLE
Unable to reference module from minIO backed registry

### ISSUE THREAD

**Issue by wortner** [TierMobility/boring-registry#73]
I have minio server running and I successfully uploaded my module, but so far I am not able to reference the module in my TF code. 
I'm not sure about the proper content for source field in my TF module definition and proper TF configuration. In readme of boring-registry the registry module is referenced just by `source="boring-registry/....."`. But how is it resolved to my local registry? Using my IP ` source="http://<IP>:9000/...."`.
 I am getting 403 or by using `source="s3::http://<IP>:9000/...."` I am getting `InvalidAccessKeyId: The AWS Access Key Id you provided does not exist in our records.`

Please advice.

**Comment by oliviermichaelis** [comment]
Hi @wortner, sorry for the late reply!

Which version of the boring-registry are you using? The latest release `0.7.0` or latest `main`?
What does your configuration look like? Could be, that you're using an API key within the registry, therefore the 403?

I'm using it like this with the latest `main`:
```hcl
module "consul_example" {
  source = "localhost:5601/hashicorp/consul/aws"
  version = "0.11.0"
}
```
or 
```hcl
module "consul_example" {
  source = "boring-registry.example.com/hashicorp/consul/aws"
  version = "0.11.0"
}
```
behind a reverse proxy

**Comment by wortner** [comment]
Maybe the setup I am using is wrong.

- running `./minio server registry`
- I have been able to upload to Minio my module
- now I try to run `boring-registry server --storage-s3-bucket=registry --storage-s3-pathstyle=true --storage-s3-endpoint=http://localhost:9000 --storage-s3-region=us-west-2` having AWS_DEFAULT_REGION, AWS_SECRET_ACCESS_KEY, AWS_ACCESS_KEY_ID set to service account created in minio GUI
- running `terraform init` with localhost gives ` download not supported for scheme 'localhost'`

**Comment by oliviermichaelis** [comment]
Thanks!

The `download not supported for scheme 'localhost'` message suggests that the schema is not valid. To be honest, I haven't tested `localhost` out, as my setup is a little different.
I think I had this problem before as well. I needed a name with multiple dots:
```
Module "consul_example" (declared at main.tf line 3) has invalid source address "localhost:5601/hashicorp/consul/aws": invalid module registry hostname: must contain at least one dot.
```
Another problem is that with `source = "127.0.0.1:5601/hashicorp/consul/aws"`, Terraform is using HTTPS, so you need to pass a valid certificate with `--tls-cert-file=self-signed.crt` and `--tls-key-file=self-signed.key`.

I'm using boring-registry behind a reverse proxy with a certificate from let's encrypt :)

**Comment by wortner** [comment]
It is taking so much time just for being able to run TF locally. Can you please elaborate more on how do you setup your proxy?

**Comment by oliviermichaelis** [comment]
I agree, Terraform registries are not really made to be run locally. In that case it's probably easier to use [local paths](https://www.terraform.io/language/modules/sources#local-paths).

Personally, I run boring-registry on Kubernetes behind [`ingress-nginx`](https://github.com/kubernetes/ingress-nginx). [`cert-manager`](https://cert-manager.io/docs/) takes care of issueing a certificate from Let's Encrypt. I'm sure many other people do run it in a similar way.

For local testing, I'm generating the certificates with:
```bash
#!/usr/bin/env bash
set -eu
org=host.example.com
domain=host.example.com

sudo trust anchor --remove self-signed.crt || true

openssl genpkey -algorithm RSA -out self-signed.key
openssl req -x509 -key self-signed.key -out self-signed.crt \
    -subj "/CN=$domain/O=$org" \
    -days 365 \
    -config <(cat /etc/ssl/openssl.cnf - <<END
[ x509_ext ]
basicConstraints = critical,CA:true
subjectKeyIdentifier = hash
authorityKeyIdentifier = keyid:always,issuer
subjectAltName = DNS:$domain
END
    ) -extensions x509_ext

sudo trust anchor self-signed.crt
```
This generates a self-signed certificate and loads it into the trust anchor of the operating system (linux in my case) so that Terraform trusts the self-signed certificate. I then run boring-registry with
```bash
boring-registry server
--tls-cert-file=self-signed.crt
--tls-key-file=self-signed.key
--storage-s3-region=eu-east-1
--storage-s3-bucket=boring-registry-test
--storage-s3-endpoint=https://minio.example.com
--storage-s3-pathstyle=true
```

The Terraform module source is specified like this:
```hcl
module "consul_example" {
  source = "host.example.com:5601/hashicorp/consul/aws"
  version = "0.11.0"
}
```

The `example.com` is my own domain in that case, and `host.example.com` resolves to the machine where boring-registry is running. Similarly, `minio.example.com` points to my minIO installation. Hope that helps, let me know if you have any other questions

**Comment by wortner** [comment]
I would be happy using just override files. But it is not possible to override just the source, the version is still merged in and local does not work with versions.

**Comment by oliviermichaelis** [comment]
I'm not familiar with your use-case and problem you're trying to solve. It sounds like you're in a complex situation, though. Not sure how I can help you here unfortunately

**Comment by wortner** [comment]
I'm getting some strange communication using cert generated by your script. So far I will give up.  Thanks for valuable help.
```
│ Error: Failed to download module
│ 
│ Could not download module "firewall_rules_external" (external-rules_override.tf:1) source code from "https://host.example.com/azurerm/company/firewall-rules": error downloading 'https://host.example.com/azurerm/company/firewall-rules': Get
│ "https://host.example.com/azurerm/company/firewall-rules?terraform-get=1": dial tcp 182.78.122.11:443: connect: connection refused
╵

╷
│ Error: Failed to download module
│ 
│ Could not download module "firewall_rules_internal" (internal-rules_override.tf:1) source code from "https://host.example.com:5601/azurerm/company/firewall-rules": error downloading 'https://host.example.com:5601/azurerm/company/firewall-rules': Get
│ "https://host.example.com:5601/azurerm/company/firewall-rules?terraform-get=1": x509: certificate signed by unknown authority
╵

**Comment by oliviermichaelis** [comment]
The `dial tcp 182.78.122.11:443: connect: connection refused` indicates that there is no port exposed or process listening on port `443`. And `x509: certificate signed by unknown authority` indicates that Terraform is not able to find the certificate in the trusted store of the OS.

If you give up, feel free to close the issue. I'm glad you tried it. Best of luck!
